#!/usr/bin/env python3
"""Every word our real translation target actually needs must have a
documented fate — and every rejected one must have a documented
EQUIVALENT.

Ranked by docs/triage-oov-lemmas.tsv (generated by `cargo run -p triage`):
the full list of (lemma, gold UPOS) pairs triage found missing from the
Lexicon while scoring the real UD-EWT corpus, ranked by how often each
one actually occurred. This replaced zipf word-frequency as the ranking
source on 2026-09-12 — real translation need, not generic English
frequency, is what "how badly do we need this word" should mean for a
project whose job is translating real sentences. Only open-class UPOS
(NOUN/VERB/ADJ/ADV/INTJ) are in scope here: the closed-class OOV (PRON,
AUX, DET, SCONJ, ADP, PART, CCONJ, NUM) is a grammar-completeness
question, not a vocabulary one, and stays a separate, tracked-but-not-
gated concern (see the report's own "OOV by gold UPOS" breakdown).

docs/vocabulary-candidates.yaml is still the ledger every word's fate is
recorded in (scripts/vocab-candidates.py's thesaurus-derived pool) — this
script only changed which words it enforces coverage for and in what
order, not where the record lives.

Stage 1 (--top, default 250): each candidate in that range must be
enabled (seed/definitions, seed.json, or a vocabulary pack) or carry a
`rejected` reason.

Stage 2, added 2026-09-11 per an explicit directive ("we have to have an
equivalent, period"): every REJECTED word in that same range must also
record what a writer should use instead — one of:
  redirect: "<word>"        an already-enabled word/lemma that covers it
  redirect_note: "<text>"   no single word substitutes (e.g. a banned
                             epistemic hedge, or a discourse particle
                             with no lexical content) — the strategy to
                             use instead
  gap: true                 genuinely searched, no existing equivalent yet
                             — an honest, recorded absence, NOT a
                             permanent verdict; re-check as the
                             vocabulary grows (same as a lexicon Gap)
  excluded: true             a deliberate, permanent design decision —
                             this concept will never be added, on
                             principle, not because nothing covers it
                             yet (e.g. "dozen": a non-decimal count word,
                             against the language's own digits-only
                             philosophy, ADR 0022). The candidate-ledger
                             parallel to a lexicon-level Ban: distinct
                             from `gap`, which stays open to
                             reconsideration; `excluded` is closed.
The only entries exempt from stage 2 are real garbage (not a word) or
proper nouns/demonyms/honorifics — tagged `exempt: "garbage"` or
`exempt: "proper-noun"`.

Lower-frequency candidates (beyond --top) stay an honest, unenforced
backlog — same policy as the vocab-ratchet process's own "automated
only, skip manual review at the tail" call.

Usage:
  python3 scripts/candidate-coverage-check.py            # gate, top 250
  python3 scripts/candidate-coverage-check.py --top 500  # gate, top 500
"""
import argparse
import glob
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
OPEN_CLASS_UPOS = {"NOUN", "VERB", "ADJ", "ADV", "INTJ"}


def load_enabled():
    """Every enabled Surface Form, not just lemmas — an irregular inflection
    (e.g. "best" as good's ADJ_SUP, "men" as man's NOUN_PL) is just as
    enabled as its lemma, and candidates are surfaced by surface spelling."""
    enabled = set()
    with open(ROOT / "lexicon.tsv") as f:
        for line in f:
            if line.startswith("#"):
                continue
            parts = line.rstrip("\n").split("\t")
            if len(parts) == 4 and parts[1] == "form":
                enabled.add(parts[0])
    return enabled


def load_oov_counts():
    """lemma -> total real occurrences in the UD-EWT OOV list, summed
    across every open-class UPOS reading (a lemma can appear more than
    once, e.g. "back" as NOUN/ADV/VERB — the sum is "how badly do we
    need this lemma", not any one specific reading of it)."""
    counts = {}
    with open(ROOT / "docs" / "triage-oov-lemmas.tsv") as f:
        for line in f:
            if line.startswith("#"):
                continue
            lemma, upos, n = line.rstrip("\n").split("\t")
            if upos not in OPEN_CLASS_UPOS:
                continue
            counts[lemma] = counts.get(lemma, 0) + int(n)
    return counts


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--top", type=int, default=250)
    args = ap.parse_args()

    cands = yaml.safe_load((ROOT / "docs" / "vocabulary-candidates.yaml").read_text())
    enabled = load_enabled()
    oov_counts = load_oov_counts()

    ranked = sorted(oov_counts, key=lambda w: -oov_counts[w])
    top = ranked[: args.top]
    rank_of = {w: i for i, w in enumerate(ranked)}

    # a word absent from the ledger entirely (never a thesaurus-ratchet
    # candidate — real corpus need found it, not the WordNet-derived pool)
    # is exactly as unresolved as one that's present with no `rejected`.
    unresolved = [w for w in top if w not in enabled and not cands.get(w, {}).get("rejected")]
    rejected = [w for w in top if w not in enabled and cands.get(w, {}).get("rejected")]

    equiv_fields = ("redirect", "redirect_note", "gap", "excluded")
    exempt = [w for w in rejected if "exempt" in cands[w]]
    no_equivalent = [w for w in rejected if "exempt" not in cands[w]
                      and not any(f in cands[w] for f in equiv_fields)]

    print(f"top {args.top} candidates by real UD-EWT translation need: "
          f"{sum(1 for w in top if w in enabled)} enabled, "
          f"{len(rejected)} rejected-with-reason, "
          f"{len(unresolved)} unresolved; "
          f"of the rejected: {len(exempt)} exempt (garbage/proper-noun), "
          f"{len(rejected) - len(exempt) - len(no_equivalent)} have a recorded equivalent, "
          f"{len(no_equivalent)} missing one")

    fail = False
    if unresolved:
        fail = True
        print(f"\nFAIL: {len(unresolved)} of the top {args.top} candidates have neither been "
              f"enabled nor given a `rejected` reason in docs/vocabulary-candidates.yaml "
              f"(some may be missing from the ledger entirely):", file=sys.stderr)
        for w in unresolved:
            in_ledger = "in ledger" if w in cands else "NOT IN LEDGER"
            print(f"  {w} (rank {rank_of[w] + 1}, {oov_counts[w]} real occurrences, {in_ledger})",
                  file=sys.stderr)

    if no_equivalent:
        fail = True
        print(f"\nFAIL: {len(no_equivalent)} rejected candidates have no recorded equivalent "
              f"(`redirect`, `redirect_note`, or `gap`) and aren't `exempt`:", file=sys.stderr)
        for w in no_equivalent:
            print(f"  {w} (rank {rank_of[w] + 1}, {oov_counts[w]} real occurrences)", file=sys.stderr)

    return 1 if fail else 0


if __name__ == "__main__":
    sys.exit(main())
